### ISSUE TITLE
Incorporate a tool for static site generation

### ISSUE THREAD

**Issue by veselosky** [webquills/webquills#11]
## Tasks

- [ ] `HUGO_THEMES_ROOT` setting
- [ ] `addtheme` management command
- [ ] `HugoTheme` model
- [ ] `HUGO_SITES_ROOT` settings
- [ ] `addsite` management command
- [ ] `HugoSite` model

## Hugo Backend

Let's face it, Hugo is crazy fast, and I'll never be able to beat its performance with home-grown Python. It's fully capable of generating HTML, RSS feeds, and sitemaps out of the box. Taxonomy support is a plus over Common Content. There are existing themes to build from.

### Themes
Themes should be installed separately from WebQuills itself. Since they are reusable for any Hugo installation, they should be packaged as Hugo expects (a git repo with a theme.toml file). This means part of the WebQuills setup process will be to install at least one theme.

Since themes are not included, WQ will need a way to know where to mount themes from. We should not dictate how self-hosting users organize their themes, but we also want to make it easy and convenient to add (or remove) themes. That implies:

- A single directory that WQ will inspect to find themes
- A way to specify a theme to load from a different location

If we keep themes in the database, this allows us to:

- have a `THEMES_ROOT` setting that WQ automatically checks at start, syncing the DB with the file system (a common motif in WQ)
- have a management command `addtheme <PATH>` that can load a theme from any accessible path.

Theme metadata would come from the `theme.toml` file.

#### Do we need themes to be installable at run time?
I don't think we need user installable themes. As a service provider, I don't want users uploading sub-standard themes. If a user really wants to customize their own site, that's fine, we can allow uploads to the layouts folder. But if the service is to keep its promise to users, supported themes need to be checked for XSS, A11Y, i18n, etc. Anyone who is self-hosting can change the settings file on their own.

### Site Editor
Since Hugo works from static files, the file system will be our integration point. As with themes, we'll keep metadata about Hugo sites in the database, with a `SITES_ROOT` setting telling us where to read and write site data, and an `addsite` management command to add sites that are not under the SITES_ROOT

When you create a new site through the UI, we create a directory structure for the site with a Hugo config file. Each site will have its own 

- `archetypes` - We won't use this, but should include it for take-outs.
- `content` - Content will be stored as Page Bundles, each with its own Resources.
- `assets` - Uploaded media (symlink to a sub-dir of Django's media dir, see below under Media)
- `data` - For future use.
- `i18n` - For future use.
- `layouts` - For future use, custom layouts uploaded by user. Normally layouts are provided by themes.
- `static` - Not used?
 
The Site editor will allow editing certain fields of the Hugo config file (most stuff will be pre-configured by the system). Fields for the Site editor:

- Title -- Human readable title
- Subtitle or Tagline -- Because most themes use one. Store in Params.
- Base URL -- The WebQuills subdomain (actual value calculated based on input).
- Language -- Populate the `languageCode` and `defaultContentLanguage`
- Copyright -- Custom copyright statement
- Summary Length -- `summaryLength` controls number of words in auto-generated Summary
- Time Zone
- Articles per Page -- `pagination.pagerSize`
- Theme

### Menu Editor
A separate Menu editor can fill in the `menus` and `sectionPagesMenu` settings.

### Page Editor
The Page Editor would output Markdown files into the `content` directory, with appropriate YAML frontmatter. Pre-designed blocks can be inserted via shortcodes (each shortcode will need its own form for data entry).

Site rebuilds will happen at publish time. We can keep a table in the database to track future publish/expire times and schedule jobs to rebuild sites that need it.

While drafting, we can build a "preview" version of the site into a separate directory for the user to see their changes (we'll need a view to expose this).

### Media Management
Django keeps a single `media` directory into which all uploads go (you can customize the subdir for each upload). Hugo prefers to keep media like images in the same directory as the page content, "page bundles". To truly leverage Hugo's abilities, we NEED to use Page Bundles with Page Resources, which means it needs the images in the bundle dir. BUT in order to enable editing, Django also needs to be able to serve the files from its `media`. So the best bet is going to be to symlink Django's media file into the bundle dir. These files will need to be treated as immutable, that is, they cannot be replaced, only added and removed.

So conceptually, the Django app would manage a site-wide library of images, and it would expose them to Hugo only as page resources, so Hugo need not know or care about the library as a whole. The user can browse and search the library via Django, but Hugo would only see the image when the user adds the image to a page. Django would also know every page using an image, so it could prevent deletion of images that are in use, and offer the ability to clean up unused images to save disk space.

The key here is that the edit interface should not allow images to be linked to the bundle unless they are actually used in the page, which is feasible.

## Refs

- https://github.com/wagtail/wagtail-bakery but I don't like how invasive this bakery thing is
- https://github.com/meeb/django-distill is much less intrusive, I think we should try this
